%{?scl:%scl_package nodejs-combined-stream}
%{!?scl:%global pkg_name %{name}}
%{?nodejs_find_provides_and_requires}

Name:           %{?scl_prefix}nodejs-combined-stream
Version:        0.0.4
Release:        4.sc1%{?dist}
Summary:        A stream that emits multiple other streams one after another
BuildArch:      noarch

Group:          System Environment/Libraries
License:        MIT
URL:            https://github.com/felixge/node-combined-stream
Source0:        http://registry.npmjs.org/combined-stream/-/combined-stream-%{version}.tgz
BuildRoot:      %{_tmppath}/%{pkg_name}-%{version}-%{release}-root-%(%{__id_u} -n)

BuildRequires:  %{?scl_prefix}nodejs-devel

%description
A stream that emits multiple other streams one after another.

%prep
%setup -q -n package

%build
#nothing to do

%install
rm -rf %buildroot
mkdir -p %{buildroot}%{nodejs_sitelib}/combined-stream
cp -pr package.json lib %{buildroot}%{nodejs_sitelib}/combined-stream
%nodejs_symlink_deps

%clean
rm -rf %buildroot

%files
%defattr(-,root,root,-)
%{nodejs_sitelib}/combined-stream
%doc License Readme.md

%changelog
* Tue Mar 04 2014 Tomas Hrcka <thrcka@redhat.com> - 0.0.4-4
- Add missing macro %nodejs_symlink_deps

* Thu Oct 17 2013 Tomas Hrcka <thrcka@redhat.com> - 0.0.4-3
- replace provides and requires with macro

* Thu Apr 11 2013 Stanislav Ochotnicky <sochotnicky@redhat.com> - 0.0.4-2
- Add support for software collections

* Sat Feb 09 2013 T.C. Hollingsworth <tchollingsworth@gmail.com> - 0.0.4-1
- new upstream release 0.0.4

* Tue Jan 08 2013 T.C. Hollingsworth <tchollingsworth@gmail.com> - 0.0.3-2
- add missing build section

* Mon Dec 31 2012 T.C. Hollingsworth <tchollingsworth@gmail.com> - 0.0.3-1
- initial package generated by npm2rpm
